### ISSUE TITLE
Automate publish step

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/devtools#65]
Automation for publishing Chrome extension and Firefox add-on, similarly to https://github.com/fregante/browser-extension-template/blob/main/.github/workflows/release.yml

If there's an agreement, I'm happy to explore and contribute the changes to accommodate this.

**Comment by photodow** [comment]
Feel free to explore this approach. Something like this would be helpful in keeping the app up to date on the marketplace. Let me know what you need from me!

**Comment by photodow** [comment]
Here is the Chrome Web Store API documentation.

https://developer.chrome.com/docs/webstore/using_webstore_api/

**Comment by photodow** [comment]
Looking at some of the options and documentation a little more closely the heavy lifting of this was getting all the appropriate tokens, and since I had a little time today I went ahead and wrapped this up. [2.4.5 (release)](https://github.com/carbon-design-system/devtools/releases/tag/2.4.5) was our first automated release really making this process so much easier. Thank you so much for pointing me in the right direction here!
